# Generated by Django 2.1.5 on 2019-01-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_3xbit', '0002_remove_user_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='source_addres',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
