# Generated by Django 2.1.5 on 2019-01-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_3xbit', '0003_auto_20190123_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wallet',
        ),
        migrations.AlterField(
            model_name='user',
            name='source_addres',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
