# Generated by Django 2.1.5 on 2019-01-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_3xbit', '0004_auto_20190123_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
